### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by JPArriola** [JPArriola/Yulp#2]
- [x] Users can login, sign-in, and sign-out
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by Carly-Schaaf** [comment]
Hey Josh, your styling looks great! Here are a few more things to address:

- [x]  Errors should clear when moving between /signup and /login
- [x] The signup button on the main page does not route to the signup form
- [x] Your "yelp" logo on the login and signup forms should route to your root route "/"

**Comment by JPArriola** [comment]
Hey Carly, all these issues have been addressed. Thank you!

**Comment by Carly-Schaaf** [comment]
Hey - so two things:

- [x] demo login is not working
- [x] your password input on the login form should have a type="password" so that the password is hidden

**Comment by JPArriola** [comment]
Hey Carly, these issues have been fixed. Thank you!

**Comment by Carly-Schaaf** [comment]
Hey Josh, your styling looks really good. Just a few more things: 
- [x] For some reason, your sign-up page isn't allowing me to sign up (you're getting "this.props.signup is not a function")
- [x] You should style your errors -- on second thought, it looks like Yelp has those pop-up errors attached to each input box, so I think you should just add a required="required" on each input and scrap your session errors all together
- [x] Lastly, I think your "Demo Login" button on the main page should just directly login the demo user, rather than take you to the sign-in page

**Comment by JPArriola** [comment]
Hey Carly, this has been updated and fixed. Thanks!
